[project]
name = "n8n-conversation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit<3.0",
    "httpx>=0.28.1"
]

[dependency-groups]
dev = [
    "isort>=7.0.0",
    "ruff>=0.14.0",
]
